_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
backbone:
    value: resnet18
batch_size:
    value: 4
checkpoint_dir:
    value: checkpoints
data_root:
    value: data/pascal_voc
debug:
    value: false
img_size:
    value:
        - 256
        - 256
lr:
    value: 0.0005
model_type:
    value: hyperbolic
no_wandb:
    value: false
num_classes:
    value: 21
num_epochs:
    value: 200
num_workers:
    value: 2
save_model:
    value: false
wandb_entity:
    value: null
wandb_name:
    value: null
wandb_project:
    value: fully-hyperbolic-segmentation
weight_decay:
    value: 1e-05
